name: Build and Deploy .NET Project

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  NET-build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout CK_Website Code'
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  Docker-deploy:
    needs: NET-build
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout CK_Website Code'
      uses: actions/checkout@v4
    - name: Set timestamp for tag
      run: |
        echo "TIME_TAG=$(date +%Y%m%d_%H%M%S)" >> "$GITHUB_ENV"
        echo $TIME_TAG
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/ck_website:website_$TIME_TAG
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/ck_website:website_$TIME_TAG

    

